### ISSUE TITLE
Decide on New Host

### ISSUE THREAD

**Issue by margaret-frechette** [SienaCollegeSoftwareEngineering/SoS_Augmented_Reality#512]
As a developer, I want to decide on a new database host due to Planetscale shutting down. 

Acceptance Criteria:
-Collectively decide on a new database host that will meet the needs of our project

Definition of Done:
- Acceptance Criteria have been met
- Moved to done by the developer and reviewed and closed by the product owner

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.
